# mir_core/beats/__init__.py
"""Beat tracking submodule - experiments, evaluation, and shared schemas."""

from .schema import (
    BEAT_CHANNEL,
    BEAT_FRAME_CLASS,
    DOWNBEAT_CHANNEL,
    DOWNBEAT_FRAME_CLASS,
    DOWNBEAT_POSITION,
    EVENT_ACTIVATION_DEFINITION,
    EVENT_CHANNEL_NAMES,
    EVENT_CHANNEL_ORDER,
    FRAME_CLASS_DEFINITION,
    FRAME_CLASS_NAMES,
    FRAME_CLASS_ORDER,
    NON_BEAT_FRAME_CLASS,
    NUM_EVENT_CHANNELS,
    NUM_FRAME_CLASSES,
    PAD_FRAME_CLASS,
    UNKNOWN_ACTIVATION,
    BeatDataDefinition,
    BeatDataRepresentation,
    EventChannel,
    FrameClass,
    annotation_to_event_activations,
    annotation_to_frame_classes,
    coerce_beat_data_definition,
    data_to_event_activations,
    event_activations_to_frame_class_activations,
    event_activations_to_frame_classes,
    frame_class_activations_to_event_activations,
    frame_classes_to_event_activations,
    times_to_activation,
)

__all__ = [
    "BEAT_CHANNEL",
    "BEAT_FRAME_CLASS",
    "DOWNBEAT_CHANNEL",
    "DOWNBEAT_FRAME_CLASS",
    "DOWNBEAT_POSITION",
    "EVENT_ACTIVATION_DEFINITION",
    "EVENT_CHANNEL_NAMES",
    "EVENT_CHANNEL_ORDER",
    "FRAME_CLASS_DEFINITION",
    "FRAME_CLASS_NAMES",
    "FRAME_CLASS_ORDER",
    "NON_BEAT_FRAME_CLASS",
    "NUM_EVENT_CHANNELS",
    "NUM_FRAME_CLASSES",
    "PAD_FRAME_CLASS",
    "UNKNOWN_ACTIVATION",
    "BeatDataDefinition",
    "BeatDataRepresentation",
    "EventChannel",
    "FrameClass",
    "annotation_to_event_activations",
    "annotation_to_frame_classes",
    "coerce_beat_data_definition",
    "data_to_event_activations",
    "event_activations_to_frame_class_activations",
    "event_activations_to_frame_classes",
    "frame_class_activations_to_event_activations",
    "frame_classes_to_event_activations",
    "times_to_activation",
]
